#!/usr/bin/env bash
#tell the story
IFS=":"


while read -r username password user_id group_id gecos home_directory shell

do

printf "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell.\n"
printf "$user_id's place is protected by the passcode $password, more info about the user here: $gecos\n"
echo ""

done < /etc/passwd
