#!/usr/bin/env bash
#tell the story
IFS=":"


while read -r username password group_id user_id_info home_directory shell

do

  echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell."

  echo "User ID's place is protected by the passcode $password, more info about the user here: $user_id_info"

  echo ""

done < /etc/passwd
