#!/usr/bin/env bash
# Group visitors by IP and HTTP status code
awk 'NF>=3{a[$1,$3]++} END {if (length(a)>0) {for (i in a) {split(i,b,SUBSEP); printf "%s %s %s\n",a[i],b[1],b[2]}} else print "ERROR: Incorrect log file format"}' < Apache-log-file | sort -nr
