#!/usr/bin/env bash
# Loop eliminating some iterations anad replacing them
i=1
while [ $i -le 10 ]
do 
echo "Best School"
if [ $i == 4 ];
then
printf "bad luck"

elif [ $i == 8 ];
then
printf "good luck"

fi

i=$((i+1))
done
