#!/usr/bin/env bash
#hours
hour=0
minute=1
while [ $hour -lt 13 ] || [ $minute -lt 60 ] 
do
echo "Hour: $hour"
hour=$(( hour+1))

echo "$minute"
minute=$(( minute+1))
done
minute=1
hour=$((hour + 1))
