#!/usr/bin/env bash
#real
ps -e -o user,pid,%cpu,%mem,rss,tty,stat,start,time,cmd --forest | awk '{printf "%-8s %-5s %-4s %-4s %-6s %-4s %-4s %-7s %-5s %%s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}'
