#!/usr/bin/env bash
#comment                                                
echo $$ > /var/run/myscript.pid
trap "rm -f /var/run/myscript.pid" SIGQUIT SIGTERM
while true;
do
echo "To infinity and beyond"
trap 'echo "I hate the kill command"' 15
done
