#!/usr/bin/env bash
#comment 
script="/var/run/myscript.pid"
echo $$ > "$script"
trap 'echo "I hate the kill command"; rm "$script"; exit' SIGTERM SIGQUIT
while true;
do
        echo "To infinity and beyond"
done	
