#!/usr/bin/env bash
#comment
trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me"' 2
echo $$ > /var/run/myscript.pid
trap 'rm -f "/var/run/myscript.pid"; exit' 3
while true;
do
echo "To infinity and beyond"
done
