#!/usr/bin/env bash
#Honestly i don't even know what i am doing
script=/var/run/my_process.pid
if [ "$1" == "start" ];
then
   ./manage_my_process &
   sudo bash -c "echo $! > $script"
   echo "manage_my_process started"
elif [ "$1" == "stop" ];
then
   pkill -f ./manage_my_process
   sudo rm $script
   echo "manage_my_process stopped"
elif [ "$1" == "restart" ];
then
   pkill -f ./manage_my_process 
   sudo rm $script
   ./manage_my_process &
   sudo bash -c "echo $! > $script"
   echo "manage_my_process restarted"
else
   echo "Usage: manage_my_process {start|stop|restart}"
fi
