#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process
PID=$(ps -eaf | pgrep bash ./4-to_infinity_and_beyond | pgrep -v pgrep | awk '{print $2}')

if [[ "" !=  "$PID" ]]; then
echo "killing $PID"
kill -9 "$PID"

fi
